# Generated by Django 4.1.1 on 2022-10-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0002_remove_equipment_parameters_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment_connection",
            name="scpi_address",
            field=models.CharField(max_length=300, verbose_name="Equipment Address"),
        ),
    ]
