# Generated by Django 4.1.1 on 2022-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0004_equipment_parameter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment_detail",
            name="scpilink",
            field=models.URLField(blank=True, verbose_name="SCPI Web Link"),
        ),
    ]
