# Generated by Django 4.1.1 on 2022-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0005_alter_equipment_detail_scpilink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment_type",
            name="measurement_equipment",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="equipment_type",
            name="source_equipment",
            field=models.BooleanField(blank=True),
        ),
    ]
