# Generated by Django 4.1.1 on 2022-10-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0006_alter_equipment_type_measurement_equipment_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="equipment_parameter", name="name",),
        migrations.RemoveField(model_name="equipment_type", name="name",),
        migrations.DeleteModel(name="Equipment_Connection",),
        migrations.DeleteModel(name="Equipment_Detail",),
        migrations.DeleteModel(name="Equipment_Parameter",),
        migrations.DeleteModel(name="Equipment_Type",),
    ]
