# Generated by Django 4.1.1 on 2022-10-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("measurements", "0007_remove_equipment_parameter_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Equipment Name"),
                ),
                (
                    "weblink",
                    models.URLField(blank=True, verbose_name="Website Address"),
                ),
                (
                    "datasheet",
                    models.URLField(blank=True, verbose_name="Datasheet Address"),
                ),
                ("scpilink", models.URLField(blank=True, verbose_name="SCPI Web Link")),
                ("current_working_status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Equipment_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("source", "Source"),
                            ("measurement", "Measurement"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measurements.equipment_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment_Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(blank=True, max_length=100)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measurements.equipment_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment_Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scpi_address",
                    models.CharField(max_length=300, verbose_name="Equipment Address"),
                ),
                ("status", models.BooleanField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measurements.equipment_detail",
                    ),
                ),
            ],
        ),
    ]
