# Generated by Django 4.1.1 on 2022-10-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0008_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment_type",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="measurements.equipment_detail",
            ),
        ),
    ]
